### ISSUE TITLE
Game crash when launching without ModTools Debug Panel

### ISSUE THREAD

**Issue by Dendraspis** [dymanoid/Skylines-ModTools#2]
When the ModTools Debug Panel is disabled this causes a game crash on startup. 
At the moment you have to enable it (and disable vanilla debug panel) every time you disabled it to prevent the crash.

I think no more informations are needed.

**Comment by dymanoid** [comment]
This is fixed with b6a954dff74e0d8c573531cd4e5edc09cdf66086.
