### ISSUE TITLE
Textfield values can't be edited or copied

### ISSUE THREAD

**Issue by Dendraspis** [dymanoid/Skylines-ModTools#3]
I didn't figured it completely out, but sometimes when you leave a textfield focused while closing its parent, the value of the textfield is inserted in every textfield you focus from this moment. It behaves like a placeholder that never appears, making you unable to change, copy or paste values. 
The only solution is finding the specific textfield, focus and unfocus it manually. Afterwards all textfields work normal.

**Comment by dymanoid** [comment]
This is already fixed with 129e6d7f273581727e3131e1fd8c44f4af08f0ff.
